---
apiVersion: v1
kind: Service
metadata:
  name: tacoservice
  namespace: gene
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: taconginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP