apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taco-ingress
  namespace: gene
spec:
  rules:
  - host: taco.apps.bingahead.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service: 
            name: tacoservice
            port: 
              number: 80
